# Generated by Django 4.0.5 on 2022-07-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OwnerName', models.CharField(max_length=30)),
                ('PetName', models.CharField(max_length=30)),
                ('PetType', models.CharField(max_length=30)),
                ('Email', models.EmailField(blank=b'I01\n', max_length=60)),
                ('City', models.CharField(blank=b'I01\n', max_length=30)),
            ],
        ),
    ]
